project:
  type: website
  output-dir: docs
  title: "Precalculus<br>MTH112, Section C <br>University of Portland, Fall 2026"


website: 
  page-navigation: true

  navbar:
    background: "#DF301C"
    search: true

  sidebar:
    search: true
    background: "#FFF1D1"
    pinned: true
    align: center

    style: docked
    collapse-level: 1

    contents:
      - href: index.qmd
        text: Welcome
      - href: info.qmd
        text: Course Information
      - href: support.qmd
        text: Student Support
      - href: content.qmd
        text: Course Content
      - href: structure.qmd
        text: Class Structure
      - href: grades.qmd
        text: Grades
      - text: "------"
      - section: "Slides"
        contents:
          - section: "Week 01"
            contents:
              - href: slides/01/01-introductions.html
                text: "Introductions"
              - href: slides/01/01-Wednesday.html
                text: "Wednesday, Week 1"
                target: _blank
              - href: slides/01/01-schedule.html
                text: "Schedule"
                target: _blank
              - href: slides/rights.html
                text: "Rights of Learners"
                target: _blank  


format:
  html:
    theme: cosmo
    css: style/mth112.scss
    toc: true
    number-sections: false
    highlight-style: monokai
    link-external-icon: true
    link-external-newwindow: true

  pdf:
    documentclass: article
    classoption: [notitlepage]
    margin-left: 30mm
    margin-right: 30mm
    toc: true
    number-sections: true
    colorlinks: true
    pdf-engine: pdflatex
    include-in-header:  
        - text: |
            \usepackage{enumitem}
